version: '3.8'

services:
  kafka:
    container_name: turkcell-kafka
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-t1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - .:/opt/jboss/keycloak/imports
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-t1
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus
    container_name: prometheus-t1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana-t1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
    networks:
      - monitor-net

  mongodb:
    container_name: turkcell-mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db/mongo

  mysql:
    container_name: turkcell-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data:/data/db/mysql

  postgresql:
    container_name: turkcell-postgresql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgresqldb_data:/data/db/postgresql


networks:
  monitor-net:
    driver: bridge

volumes:
  kafka_data:
  mongodb_data:
  mysqldb_data:
  postgresqldb_data:
  grafana_data:
  grafana_config:
