spring:
  application:
    name: filter-service
  cloud:
    config:
      profile: dev
  config: # dışarıdan alınacak yapılandırma ayarlarının kaynapını belirtir
    import: configserver:http://localhost:8888